version: '3.1'

services:
  shortlink:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    volumes:
      - ./src:/usr/src/app/src
    networks:
      - shortlink-net
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    command: npm run dev

  db:
    hostname: mongo
    image: mongo:7
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - shortlink-net
    volumes:
      - db_vol1:/data/db

networks:
  shortlink-net:
    driver: bridge

volumes:
  db_vol1:
